#!/bin/bash
#
# Build per-kernel multi-arch CUDA fatbins for the AP26 AOT (driver-only) binary,
# then emit:
#    fatbins.s  - .incbin-embeds each kernel's fatbin as a symbol (ap26fb_<k>)
#    fatbins.h  - extern decls + ap26_get_fatbin(source) keyed on the kernel
#                 source-string pointer (sieve_cl, checkn_cl, ...)
#
# Mirrors the genefer22 CUDA port's fatbin scheme. Per-arch failures are
# non-fatal (warn + skip) so the fatbin always contains whatever arches built.
#
# Env: CUDA, ARCHES_DIRECT, ARCHES_BLACKWELL
#
set -u
cd "$(dirname "$0")"

CUDA="${CUDA:-/usr/local/cuda-12.9}"
NVCC="$CUDA/bin/nvcc"; PTXAS="$CUDA/bin/ptxas"; FATBINARY="$CUDA/bin/fatbinary"

KERNELS="checkn clearn clearok clearokok offset setupn setupok setupokok sieve sieve_ilp2 sieve_mid sieve_nv"
# directly nvcc-compilable arches (Maxwell -> Hopper)
ARCHES_DIRECT="${ARCHES_DIRECT:-50 52 60 61 70 75 80 86 89 90}"
# Blackwell: compute_89 PTX -> ptxas to the sm_NNNf family target (genefer scheme)
ARCHES_BLACKWELL="${ARCHES_BLACKWELL:-100 120}"

OUT=fatbins_build
rm -rf "$OUT"; mkdir -p "$OUT"
TMP="$(mktemp -d)"
ERR=/tmp/ap26_fatbin_err.log

for k in $KERNELS; do
  cu="kernels/$k.cu"
  imgs=(); ptx="$TMP/$k.c89.ptx"

  for a in $ARCHES_DIRECT; do
    cub="$TMP/${k}_sm${a}.cubin"
    if "$NVCC" -gencode "arch=compute_${a},code=sm_${a}" --cubin "$cu" -o "$cub" 2>"$ERR"; then
      imgs+=(--image3="kind=elf,sm=${a},file=${cub}")
      # occupancy guard: the sieve variants sit on per-arch register knife-edges
      # (sm_70 2x1024 blocks need <=32 regs; sm_86/89 768x2=1536 thr need <=42).
      # Fail loudly if compiler/source drift ever pushes past the budget.
      case "$k" in sieve|sieve_mid|sieve_ilp2)
        budget=""; [ "$a" = 70 ] && budget=32; { [ "$a" = 86 ] || [ "$a" = 89 ]; } && budget=42
        if [ -n "$budget" ]; then
          regs=$("$CUDA/bin/cuobjdump" --dump-resource-usage "$cub" 2>/dev/null | grep -oP 'REG:\K[0-9]+' | head -1)
          if [ -n "$regs" ] && [ "$regs" -gt "$budget" ]; then
            echo "  !! $k sm_$a uses $regs registers (> $budget budget: occupancy cliff)"; exit 1
          fi
        fi
      ;; esac
    else
      echo "  !! $k sm_$a failed: $(tail -1 "$ERR")"
    fi
  done

  for a in $ARCHES_BLACKWELL; do
    if [ ! -s "$ptx" ]; then
      "$NVCC" -ptx -arch=compute_89 "$cu" -o "$ptx" 2>"$ERR" || { echo "  !! $k compute_89 ptx failed: $(tail -1 "$ERR")"; continue; }
    fi
    cub="$TMP/${k}_sm${a}f.cubin"
    if "$PTXAS" -arch="sm_${a}f" "$ptx" -o "$cub" 2>"$ERR"; then
      imgs+=(--image3="kind=elf,sm=${a}f,file=${cub}")
    else
      echo "  !! $k sm_${a}f failed: $(tail -1 "$ERR")"
    fi
  done

  if [ "${#imgs[@]}" -eq 0 ]; then echo "  !! $k: no arches built"; exit 1; fi
  if "$FATBINARY" --create="$OUT/$k.fatbin" --64 "${imgs[@]}" 2>"$ERR"; then
    printf "  %-12s %4s KB  (%d arches)\n" "$k" "$(( $(stat -c%s "$OUT/$k.fatbin")/1024 ))" "${#imgs[@]}"
  else
    echo "  !! fatbinary $k failed: $(cat "$ERR")"; exit 1
  fi
done

# ---- emit fatbins.s (.incbin) + fatbins.h (source-ptr -> fatbin registry) ----
SF=fatbins.s; HF=fatbins.h
printf '/* auto-generated by build_fatbins.sh */\n\t.section .note.GNU-stack,"",@progbits\n\t.section .rodata\n' > "$SF"
{
  printf '// auto-generated by build_fatbins.sh - embedded multi-arch fatbins\n'
  printf '#pragma once\n'
  printf 'extern "C" {\n'
} > "$HF"

TABLE=""
for k in $KERNELS; do
  s="ap26fb_$k"
  printf '\t.global %s\n\t.align 8\n%s:\n\t.incbin "%s/%s.fatbin"\n' "$s" "$s" "$OUT" "$k" >> "$SF"
  printf '  extern const unsigned char %s[];\n' "$s" >> "$HF"
  TABLE="${TABLE}  { ${k}_cl, ap26fb_${k} },\n"
done

{
  printf '}\n'
  printf 'struct ap26_fatbin_t { const char * src; const unsigned char * data; };\n'
  printf 'static const ap26_fatbin_t ap26_fatbin_table[] = {\n%b};\n' "$TABLE"
  printf 'const void * ap26_get_fatbin(const char * source) {\n'
  printf '  for (unsigned i = 0; i < sizeof(ap26_fatbin_table)/sizeof(ap26_fatbin_table[0]); ++i)\n'
  printf '    if (ap26_fatbin_table[i].src == source) return (const void *)ap26_fatbin_table[i].data;\n'
  printf '  return (const void *)0;\n}\n'
} >> "$HF"

echo "[embed] wrote $SF + $HF  ($(ls "$OUT"/*.fatbin | wc -l) fatbins)"
rm -rf "$TMP"
