#!/bin/bash
#
# Cross-build the AP26 CUDA application for Windows x64 from Linux (MinGW-w64).
#
# The GPU side is identical to the Linux build: the same nvcc-built multi-arch
# fatbins (fatbins_build/*.fatbin) are embedded, just as bin2c C arrays instead
# of .incbin ELF assembly (COFF-friendly). The host side links:
#   - BOINC libs cross-built via BOINC's own api/lib Makefile.mingw (winlibs/)
#   - an import library for nvcuda.dll generated from the driver-API symbols
#     the app actually uses (no Windows CUDA toolkit needed)
#
# Prereqs: x86_64-w64-mingw32-g++, CUDA toolkit (nvcc/bin2c) for the fatbins,
# BOINC source. Run ./build.sh --fatbin (or this script builds fatbins itself).
#
# Env overrides: CUDA, BOINC_DIR, MINGW
#
set -e
cd "$(dirname "$0")"

CUDA="${CUDA:-/usr/local/cuda-12.9}"
BOINC_DIR="${BOINC_DIR:-/home/ian/builds/boinc}"
MINGW="${MINGW:-x86_64-w64-mingw32}"
VER="23_5_6"
W=winlibs
APP="ap27_win64_cuda.exe"

CXX="$MINGW-g++"
KERNELS="checkn clearn clearok clearokok offset setupn setupok setupokok sieve sieve_ilp2 sieve_mid sieve_nv"

# 0. BOINC windows libs (build once; see winlibs/shim for the config shim)
if [ ! -f "$W/libboinc.a" ] || [ ! -f "$W/libboinc_api.a" ]; then
  echo "[boinc] cross-building BOINC libs into $W/"
  mkdir -p "$W/shim"
  [ -f "$W/shim/config.h" ] || cat > "$W/shim/config.h" <<'EOF'
#ifndef BOINC_MINGW_CONFIG_H
#define BOINC_MINGW_CONFIG_H
#define HAVE_STRCASECMP 1
#define HAVE__STRICMP 1
#define HAVE_STRDUP 1
#endif
EOF
  [ -f "$W/shim/force.h" ] || printf '#include <stddef.h>\n#include <string.h>\n#include "%s/lib/str_replace.h"\n' "$BOINC_DIR" > "$W/shim/force.h"
  ( cd "$W" && MINGW="$MINGW" BOINC_SRC="$BOINC_DIR" \
      make -f "$BOINC_DIR/lib/Makefile.mingw" \
        INCS="-I$(pwd)/shim -I$BOINC_DIR -I$BOINC_DIR/db -I$BOINC_DIR/lib -I$BOINC_DIR/api -I$BOINC_DIR/zip -I$BOINC_DIR/win_build" \
        OPTFLAGS="-O3 -include $(pwd)/shim/force.h" \
        libboinc.a libboinc_api.a )
fi

# 1. kernel source-string headers (same as Linux build)
echo "[cltoh] generating kernel source headers"
for k in $KERNELS; do perl cltoh.pl "kernels/$k.cu" > "kernels/$k.h"; done

# 2. fatbins (reuse if present; identical to the Linux binary's)
if [ ! -d fatbins_build ] || [ -z "$(ls fatbins_build/*.fatbin 2>/dev/null)" ]; then
  echo "[fatbin] building fatbins with nvcc"
  bash ./build_fatbins.sh
fi

# 3. embed fatbins as C arrays (COFF-safe replacement for fatbins.s/.incbin).
#    OVERWRITES the generated fatbins.h; the Linux build regenerates its own.
echo "[bin2c] embedding fatbins as C arrays -> fatbins.h"
{
  printf '// auto-generated by build_win.sh - fatbins embedded as C arrays\n#pragma once\n'
  for k in $KERNELS; do
    "$CUDA/bin/bin2c" --const --type char --name "ap26fb_$k" "fatbins_build/$k.fatbin"
  done
  printf 'struct ap26_fatbin_t { const char * src; const void * data; };\n'
  printf 'static const ap26_fatbin_t ap26_fatbin_table[] = {\n'
  for k in $KERNELS; do printf '  { %s_cl, (const void *)ap26fb_%s },\n' "$k" "$k"; done
  printf '};\n'
  printf 'const void * ap26_get_fatbin(const char * source) {\n'
  printf '  for (unsigned i = 0; i < sizeof(ap26_fatbin_table)/sizeof(ap26_fatbin_table[0]); ++i)\n'
  printf '    if (ap26_fatbin_table[i].src == source) return ap26_fatbin_table[i].data;\n'
  printf '  return (const void *)0;\n}\n'
} > fatbins.h

# 4. compile the host
echo "[cc] AP26.cpp (mingw)"
BINC="-I$W/shim -I$BOINC_DIR -I$BOINC_DIR/api -I$BOINC_DIR/lib -I$BOINC_DIR/win_build"
$CXX -I . -I kernels -I "$CUDA/include" $BINC -O3 -m64 -DVERS=\"$VER\" \
     -DAP26_EMBED_FATBINS -c -o AP26_win.o AP26.cpp

# 5. import library for nvcuda.dll from the symbols the object actually needs
echo "[nvcuda] generating import library"
"$MINGW-nm" -u AP26_win.o | grep -oE 'cu[A-Za-z_0-9]+' | sort -u > "$W/nvcuda.syms"
{
  echo "LIBRARY nvcuda.dll"
  echo "EXPORTS"
  cat "$W/nvcuda.syms"
} > "$W/nvcuda.def"
"$MINGW-dlltool" -d "$W/nvcuda.def" -l "$W/libnvcuda.a"
echo "  $(wc -l < "$W/nvcuda.syms") driver symbols"

# 6. link
echo "[ld] $APP"
$CXX -static -static-libgcc -static-libstdc++ AP26_win.o \
     "$W/libboinc_api.a" "$W/libboinc.a" "$W/libnvcuda.a" \
     -lpsapi -lws2_32 -lwinmm -o "$APP"
echo "built: $APP"
